apiVersion: apps/v1
kind: Deployment
metadata:
  name: guardrail-deployment
  labels:
    app: guardrail
spec:
  replicas: 1
  selector:
    matchLabels:
      app: guardrail
  template:
    metadata:
      labels:
        app: guardrail
    spec:
      containers:
      - name: guardrail-container
        image: guardrail-service:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        
        # [TAMBAHAN 1] Override Command agar Auto-Reload aktif
        command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "80", "--reload"]

        env:
        - name: MODEL_NAME
          value: "treamyracle/indobert-ner-pii-guardrail"
        - name: HF_TOKEN
          valueFrom:
            secretKeyRef:
              name: infomedia-secrets
              key: HF_TOKEN
        
        readinessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 5
        
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "1"

        # [TAMBAHAN 2] Mounting Point di dalam Container
        volumeMounts:
        - name: local-code
          mountPath: /app/app  # Posisi folder codingan di dalam container

      # [TAMBAHAN 3] Definisi Folder Asli di Laptop
      volumes:
      - name: local-code
        hostPath:
          # PERHATIKAN PATH INI! Sesuaikan dengan lokasi folder 'app' di laptop Anda.
          # Format Docker Desktop Windows: /run/desktop/mnt/host/c/Users/...
          path: /run/desktop/mnt/host/c/Users/tream/OneDrive/Documents/1DEV/Infomedia_AI_Internship/guardrail_service/app
          type: Directory