apiVersion: v1
kind: Service
metadata:
  name: guardrail-service # Nama service
spec:
  type: ClusterIP # Tipe service
  selector:
    app: guardrail
  ports:
    - protocol: TCP
      port: 80       
      targetPort: 80 